### ISSUE TITLE
`COMMON_SAFE_ASCII_CHARACTERS` error due to missing package

### ISSUE THREAD

**Issue by noshbar** [kedzkiest/shap-e-local#1]
I followed the instructions in the readme, was going well, but when I first tried running `textTo3D.py` I got an error:
`ImportError: cannot import name 'COMMON_SAFE_ASCII_CHARACTERS' from 'charset_normalizer.constant' `

To fix this, I had to install the `chardet` package via:
`pip install chardet`

I'm running on Windows 10, for what it's worth.
And thanks for this!

**Comment by kedzkiest** [comment]
Hi, @noshbar 

Did you successfully generate a 3D model after installing the `chardet` package?
If so, I'm gonna close this issue.

Also, thanks for sharing the info!

**Comment by noshbar** [comment]
I did indeed! Everything worked smoothly afterwards, so close away!
